/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.CredentialDefinition = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CredentialDefinition model module.
   * @module model/CredentialDefinition
   * @version 1.0
   */

  /**
   * Constructs a new <code>CredentialDefinition</code>.
   * @alias module:model/CredentialDefinition
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CredentialDefinition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CredentialDefinition} obj Optional instance to populate.
   * @return {module:model/CredentialDefinition} The populated <code>CredentialDefinition</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('credDefId'))
        obj.credDefId = ApiClient.convertToType(data['credDefId'], 'String');
      if (data.hasOwnProperty('credDefJson'))
        obj.credDefJson = ApiClient.convertToType(data['credDefJson'], 'String');
      if (data.hasOwnProperty('credDefs'))
        obj.credDefs = ApiClient.convertToType(data['credDefs'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} credDefId
   */
  exports.prototype.credDefId = undefined;

  /**
   * @member {String} credDefJson
   */
  exports.prototype.credDefJson = undefined;

  /**
   * @member {String} credDefs
   */
  exports.prototype.credDefs = undefined;

  return exports;

}));
