/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CredentialDefinition', 'model/ProverCreateCredentialRequestResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CredentialDefinition'), require('./ProverCreateCredentialRequestResult'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.CredentialRequest = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.CredentialDefinition, root.ApiDocumentation.ProverCreateCredentialRequestResult);
  }
}(this, function(ApiClient, CredentialDefinition, ProverCreateCredentialRequestResult) {
  'use strict';

  /**
   * The CredentialRequest model module.
   * @module model/CredentialRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>CredentialRequest</code>.
   * @alias module:model/CredentialRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CredentialRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CredentialRequest} obj Optional instance to populate.
   * @return {module:model/CredentialRequest} The populated <code>CredentialRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('credOffer'))
        obj.credOffer = ApiClient.convertToType(data['credOffer'], 'String');
      if (data.hasOwnProperty('credRequest'))
        obj.credRequest = ProverCreateCredentialRequestResult.constructFromObject(data['credRequest']);
      if (data.hasOwnProperty('credentials'))
        obj.credentials = CredentialDefinition.constructFromObject(data['credentials']);
      if (data.hasOwnProperty('masterSecretId'))
        obj.masterSecretId = ApiClient.convertToType(data['masterSecretId'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} credOffer
   */
  exports.prototype.credOffer = undefined;

  /**
   * @member {module:model/ProverCreateCredentialRequestResult} credRequest
   */
  exports.prototype.credRequest = undefined;

  /**
   * @member {module:model/CredentialDefinition} credentials
   */
  exports.prototype.credentials = undefined;

  /**
   * @member {String} masterSecretId
   */
  exports.prototype.masterSecretId = undefined;

  return exports;

}));
