/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.IssuerCreateCredentialResult = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The IssuerCreateCredentialResult model module.
   * @module model/IssuerCreateCredentialResult
   * @version 1.0
   */

  /**
   * Constructs a new <code>IssuerCreateCredentialResult</code>.
   * @alias module:model/IssuerCreateCredentialResult
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>IssuerCreateCredentialResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IssuerCreateCredentialResult} obj Optional instance to populate.
   * @return {module:model/IssuerCreateCredentialResult} The populated <code>IssuerCreateCredentialResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('credentialJson'))
        obj.credentialJson = ApiClient.convertToType(data['credentialJson'], 'String');
      if (data.hasOwnProperty('revocId'))
        obj.revocId = ApiClient.convertToType(data['revocId'], 'String');
      if (data.hasOwnProperty('revocRegDeltaJson'))
        obj.revocRegDeltaJson = ApiClient.convertToType(data['revocRegDeltaJson'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} credentialJson
   */
  exports.prototype.credentialJson = undefined;

  /**
   * @member {String} revocId
   */
  exports.prototype.revocId = undefined;

  /**
   * @member {String} revocRegDeltaJson
   */
  exports.prototype.revocRegDeltaJson = undefined;

  return exports;

}));
