/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Wallet'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Wallet'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.Person = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.Wallet);
  }
}(this, function(ApiClient, Wallet) {
  'use strict';

  /**
   * The Person model module.
   * @module model/Person
   * @version 1.0
   */

  /**
   * Constructs a new <code>Person</code>.
   * @alias module:model/Person
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Person</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Person} obj Optional instance to populate.
   * @return {module:model/Person} The populated <code>Person</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('indyWallet'))
        obj.indyWallet = Wallet.constructFromObject(data['indyWallet']);
      if (data.hasOwnProperty('masterSecretId'))
        obj.masterSecretId = ApiClient.convertToType(data['masterSecretId'], 'String');
      if (data.hasOwnProperty('personDid'))
        obj.personDid = ApiClient.convertToType(data['personDid'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/Wallet} indyWallet
   */
  exports.prototype.indyWallet = undefined;

  /**
   * @member {String} masterSecretId
   */
  exports.prototype.masterSecretId = undefined;

  /**
   * @member {String} personDid
   */
  exports.prototype.personDid = undefined;

  return exports;

}));
