/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelAndView'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelAndView'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.BasicErrorControllerApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.ModelAndView);
  }
}(this, function(ApiClient, ModelAndView) {
  'use strict';

  /**
   * BasicErrorController service.
   * @module api/BasicErrorControllerApi
   * @version 1.0
   */

  /**
   * Constructs a new BasicErrorControllerApi. 
   * @alias module:api/BasicErrorControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the errorHtmlUsingDELETE operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingDELETE = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the errorHtmlUsingGET operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the errorHtmlUsingHEAD operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingHEADCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingHEADCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingHEAD = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'HEAD',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the errorHtmlUsingOPTIONS operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingOPTIONSCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingOPTIONSCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingOPTIONS = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the errorHtmlUsingPATCH operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingPATCHCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingPATCHCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingPATCH = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the errorHtmlUsingPOST operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingPOST = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the errorHtmlUsingPUT operation.
     * @callback module:api/BasicErrorControllerApi~errorHtmlUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelAndView} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * errorHtml
     * @param {module:api/BasicErrorControllerApi~errorHtmlUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelAndView}
     */
    this.errorHtmlUsingPUT = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['text/html'];
      var returnType = ModelAndView;

      return this.apiClient.callApi(
        '/error', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
