/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CredentialRequest', 'model/IssuerCreateCredentialResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/CredentialRequest'), require('../model/IssuerCreateCredentialResult'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.IssuerControllerApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.CredentialRequest, root.ApiDocumentation.IssuerCreateCredentialResult);
  }
}(this, function(ApiClient, CredentialRequest, IssuerCreateCredentialResult) {
  'use strict';

  /**
   * IssuerController service.
   * @module api/IssuerControllerApi
   * @version 1.0
   */

  /**
   * Constructs a new IssuerControllerApi. 
   * @alias module:api/IssuerControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createCredentialsUsingPUT operation.
     * @callback module:api/IssuerControllerApi~createCredentialsUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/IssuerCreateCredentialResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createCredentials
     * @param {Object} opts Optional parameters
     * @param {String} opts.JSON 
     * @param {Number} opts.age 
     * @param {String} opts.credOffer 
     * @param {String} opts.credRequestCredentialRequestJson 
     * @param {String} opts.credRequestCredentialRequestMetadataJson 
     * @param {String} opts.credentialsCredDefId 
     * @param {String} opts.credentialsCredDefJson 
     * @param {Date} opts.dateOfBirth 
     * @param {Number} opts.licenceLevel 
     * @param {String} opts.masterSecretId 
     * @param {String} opts.name 
     * @param {Number} opts.walletHandle 
     * @param {module:api/IssuerControllerApi~createCredentialsUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/IssuerCreateCredentialResult}
     */
    this.createCredentialsUsingPUT = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'JSON': opts['JSON'],
        'age': opts['age'],
        'credOffer': opts['credOffer'],
        'credRequest.credentialRequestJson': opts['credRequestCredentialRequestJson'],
        'credRequest.credentialRequestMetadataJson': opts['credRequestCredentialRequestMetadataJson'],
        'credentials.credDefId': opts['credentialsCredDefId'],
        'credentials.credDefJson': opts['credentialsCredDefJson'],
        'dateOfBirth': opts['dateOfBirth'],
        'licenceLevel': opts['licenceLevel'],
        'masterSecretId': opts['masterSecretId'],
        'name': opts['name'],
        'walletHandle': opts['walletHandle'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = IssuerCreateCredentialResult;

      return this.apiClient.callApi(
        '/create-credentials', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getProverCredentialUsingGET operation.
     * @callback module:api/IssuerControllerApi~getProverCredentialUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CredentialRequest} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getProverCredential
     * @param {Object} opts Optional parameters
     * @param {String} opts.cluelessWalletWalletId 
     * @param {String} opts.cluelessWalletWalletId2 
     * @param {String} opts.cluelessWalletWalletKey 
     * @param {String} opts.cluelessWalletWalletKey2 
     * @param {Number} opts.indyWalletWalletHandle 
     * @param {Number} opts.indyWalletWalletHandle2 
     * @param {String} opts.personDid 
     * @param {String} opts.personDid2 
     * @param {module:api/IssuerControllerApi~getProverCredentialUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CredentialRequest}
     */
    this.getProverCredentialUsingGET = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'cluelessWallet.walletId': opts['cluelessWalletWalletId'],
        'cluelessWallet.walletId': opts['cluelessWalletWalletId2'],
        'cluelessWallet.walletKey': opts['cluelessWalletWalletKey'],
        'cluelessWallet.walletKey': opts['cluelessWalletWalletKey2'],
        'indyWallet.walletHandle': opts['indyWalletWalletHandle'],
        'indyWallet.walletHandle': opts['indyWalletWalletHandle2'],
        'personDid': opts['personDid'],
        'personDid': opts['personDid2'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = CredentialRequest;

      return this.apiClient.callApi(
        '/get-prover-credentials', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
