/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CredentialRequest', function() {
      beforeEach(function() {
        instance = new ApiDocumentation.CredentialRequest();
      });

      it('should create an instance of CredentialRequest', function() {
        // TODO: update the code to test CredentialRequest
        expect(instance).to.be.a(ApiDocumentation.CredentialRequest);
      });

      it('should have the property credOffer (base name: "credOffer")', function() {
        // TODO: update the code to test the property credOffer
        expect(instance).to.have.property('credOffer');
        // expect(instance.credOffer).to.be(expectedValueLiteral);
      });

      it('should have the property credRequest (base name: "credRequest")', function() {
        // TODO: update the code to test the property credRequest
        expect(instance).to.have.property('credRequest');
        // expect(instance.credRequest).to.be(expectedValueLiteral);
      });

      it('should have the property credentials (base name: "credentials")', function() {
        // TODO: update the code to test the property credentials
        expect(instance).to.have.property('credentials');
        // expect(instance.credentials).to.be(expectedValueLiteral);
      });

      it('should have the property masterSecretId (base name: "masterSecretId")', function() {
        // TODO: update the code to test the property masterSecretId
        expect(instance).to.have.property('masterSecretId');
        // expect(instance.masterSecretId).to.be(expectedValueLiteral);
      });

    });
  });

}));
