/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('IssuerCreateCredentialResult', function() {
      beforeEach(function() {
        instance = new ApiDocumentation.IssuerCreateCredentialResult();
      });

      it('should create an instance of IssuerCreateCredentialResult', function() {
        // TODO: update the code to test IssuerCreateCredentialResult
        expect(instance).to.be.a(ApiDocumentation.IssuerCreateCredentialResult);
      });

      it('should have the property credentialJson (base name: "credentialJson")', function() {
        // TODO: update the code to test the property credentialJson
        expect(instance).to.have.property('credentialJson');
        // expect(instance.credentialJson).to.be(expectedValueLiteral);
      });

      it('should have the property revocId (base name: "revocId")', function() {
        // TODO: update the code to test the property revocId
        expect(instance).to.have.property('revocId');
        // expect(instance.revocId).to.be(expectedValueLiteral);
      });

      it('should have the property revocRegDeltaJson (base name: "revocRegDeltaJson")', function() {
        // TODO: update the code to test the property revocRegDeltaJson
        expect(instance).to.have.property('revocRegDeltaJson');
        // expect(instance.revocRegDeltaJson).to.be(expectedValueLiteral);
      });

    });
  });

}));
