/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Person', function() {
      beforeEach(function() {
        instance = new ApiDocumentation.Person();
      });

      it('should create an instance of Person', function() {
        // TODO: update the code to test Person
        expect(instance).to.be.a(ApiDocumentation.Person);
      });

      it('should have the property indyWallet (base name: "indyWallet")', function() {
        // TODO: update the code to test the property indyWallet
        expect(instance).to.have.property('indyWallet');
        // expect(instance.indyWallet).to.be(expectedValueLiteral);
      });

      it('should have the property masterSecretId (base name: "masterSecretId")', function() {
        // TODO: update the code to test the property masterSecretId
        expect(instance).to.have.property('masterSecretId');
        // expect(instance.masterSecretId).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property personDid (base name: "personDid")', function() {
        // TODO: update the code to test the property personDid
        expect(instance).to.have.property('personDid');
        // expect(instance.personDid).to.be(expectedValueLiteral);
      });

    });
  });

}));
