/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.ProverControllerApi();
  });

  describe('(package)', function() {
    describe('ProverControllerApi', function() {
      describe('proverGetDefaultCredentialsUsingGET', function() {
        it('should call proverGetDefaultCredentialsUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for proverGetDefaultCredentialsUsingGET call and complete the assertions
          /*
          var opts = {};
          opts.credDefId = "credDefId_example";
          opts.masterSecretId = "masterSecretId_example";
          opts.proverDID = "proverDID_example";
          opts.proverWalletID = "proverWalletID_example";
          opts.proverWalletKey = "proverWalletKey_example";
          opts.schemaId = "schemaId_example";

          instance.proverGetDefaultCredentialsUsingGET(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a('string');
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('proverGetProofCredentialsUsingGET', function() {
        it('should call proverGetProofCredentialsUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for proverGetProofCredentialsUsingGET call and complete the assertions
          /*
          var opts = {};
          opts.credDefId = "credDefId_example";
          opts.masterSecretId = "masterSecretId_example";
          opts.proofRequestJson = "proofRequestJson_example";
          opts.proverDID = "proverDID_example";
          opts.proverWalletID = "proverWalletID_example";
          opts.proverWalletKey = "proverWalletKey_example";
          opts.schemaId = "schemaId_example";

          instance.proverGetProofCredentialsUsingGET(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a('string');
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
