/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.WalletControllerApi();
  });

  describe('(package)', function() {
    describe('WalletControllerApi', function() {
      describe('closeWalletUsingDELETE', function() {
        it('should call closeWalletUsingDELETE successfully', function(done) {
          // TODO: uncomment, update parameter values for closeWalletUsingDELETE call
          /*
          var opts = {};
          opts.walletHandle = 56;

          instance.closeWalletUsingDELETE(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createWalletUsingPUT', function() {
        it('should call createWalletUsingPUT successfully', function(done) {
          // TODO: uncomment, update parameter values for createWalletUsingPUT call
          /*
          var opts = {};
          opts.id = "id_example";
          opts.key = "key_example";

          instance.createWalletUsingPUT(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteWalletUsingDELETE', function() {
        it('should call deleteWalletUsingDELETE successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteWalletUsingDELETE call
          /*
          var opts = {};
          opts.id = "id_example";
          opts.key = "key_example";

          instance.deleteWalletUsingDELETE(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getWalletUsingGET', function() {
        it('should call getWalletUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for getWalletUsingGET call and complete the assertions
          /*
          var opts = {};
          opts.id = "id_example";
          opts.key = "key_example";

          instance.getWalletUsingGET(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ApiDocumentation.Wallet);
            expect(data.walletHandle).to.be.a('number');
            expect(data.walletHandle).to.be(0);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
